"""Print a portable SFT/GRPO command; GPU execution requires --execute and a named GPU."""

import argparse
import json
from pathlib import Path
import shlex
import subprocess
import sys
import time

from .common import read_jsonl, sha256, unique_rows, write_json
from .convert_clevrer import assign_split
from .runtime import (add_gpu_arguments, check_versions, gpu_lease, prepare_environment,
                      require_local_model, validate_execute_arguments)


def build_command(stage, model, data, output, adapter=None, config=None):
    config_path = Path(config) if config else Path(__file__).resolve().parent / 'configs' / f'{stage}.json'
    values = json.loads(config_path.read_text(encoding='utf-8'))
    values.update(model=str(model), dataset=[str(Path(data) / f'{stage}_train.jsonl')], output_dir=str(output))
    if stage == 'grpo':
        if not adapter:
            raise ValueError('GRPO must initialize from the dev-selected SFT adapter: provide --adapter')
        values.update(adapters=[str(adapter)], ref_adapters=[str(adapter)],
                      external_plugins=[str(Path(__file__).with_name('reward_plugin.py').resolve())])
    elif adapter:
        raise ValueError('SFT starts from the base model; --adapter is only valid for GRPO')
    command = [sys.executable, '-m', 'swift.cli.sft' if stage == 'sft' else 'swift.cli.rlhf']
    for key, value in values.items():
        command.append('--' + key)
        items = value if isinstance(value, list) else [value]
        command.extend(str(item).lower() if isinstance(item, bool) else str(item) for item in items)
    return command, values, config_path


def validate_training_inputs(stage, dataset, adapter):
    rows = read_jsonl(dataset)
    if len(rows) != 12000:
        raise ValueError('Historical recipe requires the full 12000-row training split')
    unique_rows(rows)
    for row in rows:
        index = int(row['video_id'].removeprefix('video_'))
        if not 0 <= index < 10000 or assign_split(row['video_id'], source_role='official_train', seed=42, dev_ratio=.1) != 'train':
            raise ValueError('Training rows must be in the official-train video-level training split')
        if len(row.get('images', [])) != 8 or any(not Path(image).is_file() for image in row['images']):
            raise ValueError('Every training example requires eight existing extracted frames')
        roles = [message['role'] for message in row['messages']]
        if roles != (['system', 'user', 'assistant'] if stage == 'sft' else ['system', 'user']):
            raise ValueError('Unexpected prompt roles; GRPO input must not contain the reference answer')
    if adapter:
        path = Path(adapter)
        if not path.is_absolute() or not (path / 'adapter_model.safetensors').is_file():
            raise ValueError('GRPO requires an existing absolute local SFT adapter directory')
    return len(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('stage', choices=('sft', 'grpo'))
    parser.add_argument('--model', required=True)
    parser.add_argument('--data', required=True, help='Directory generated by convert_clevrer')
    parser.add_argument('--output', required=True, help='New output directory on your data disk')
    parser.add_argument('--adapter', help='Dev-selected SFT checkpoint for GRPO; historical winner was step 700')
    parser.add_argument('--config', help='JSON configuration override; changes define a new experiment')
    parser.add_argument('--max-hours', type=float, help='Required finite wall-time ceiling for --execute')
    add_gpu_arguments(parser)
    args = parser.parse_args()
    command, values, config_path = build_command(args.stage, args.model, args.data, args.output, args.adapter, args.config)
    print('DRY RUN' if not args.execute else 'EXPLICIT GPU RUN')
    print('MAX_PIXELS=50176; offline model loading; W&B disabled')
    print(shlex.join(command))
    if not args.execute:
        return
    validate_execute_arguments(args)
    if args.max_hours is None or not 0 < args.max_hours <= 160:
        raise ValueError('--execute requires 0 < --max-hours <= 160; this is a per-run ceiling, not a budget tracker')
    require_local_model(args.model)
    output = Path(args.output)
    if not output.is_absolute() or output.exists():
        raise ValueError('--output must be a new absolute directory on your data disk; overwrite is refused')
    dataset = Path(values['dataset'][0])
    validate_training_inputs(args.stage, dataset, args.adapter)
    versions = check_versions()
    environment = prepare_environment(args.cache_root, args.expected_gpu_uuid)
    with gpu_lease(args.cache_root, args.gpu, args.expected_gpu_uuid) as gpu:
        output.mkdir(parents=True)
        receipt = {'stage': args.stage, 'status': 'started', 'versions': versions, 'gpu': gpu,
                   'command': command, 'config_sha256': sha256(config_path), 'dataset_sha256': sha256(dataset),
                   'configuration': values, 'max_hours': args.max_hours,
                   'note': 'New run, not a reproduction claim. Original machine-specific orchestration was not retained.'}
        write_json(output / 'launch.json', receipt)
        started = time.monotonic()
        status, returncode = 'failed', None
        try:
            with (output / 'train.log').open('x', encoding='utf-8') as log:
                result = subprocess.run(command, env=environment, stdout=log, stderr=subprocess.STDOUT,
                                        timeout=args.max_hours * 3600, check=False)
            returncode = result.returncode
            status = 'completed' if returncode == 0 else 'failed'
        except subprocess.TimeoutExpired:
            status = 'wall_time_limit'
            raise
        finally:
            write_json(output / 'exit.json', {'status': status, 'returncode': returncode,
                                             'wall_seconds': time.monotonic() - started})
        if returncode:
            raise SystemExit(returncode)


if __name__ == '__main__':
    main()
